### ISSUE TITLE
Lab 4, Ex 3, Task 3.2 account disabled

### ISSUE THREAD

**Issue by ervee** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#59] opened 2021-03-01 12:42 UTC
# Module: AZ-304
#### Step: 2

Description of issue:
During this Task/step I could not login to the myapplications URL. After tracing back my steps and checking the account I notices the account was disabled. I could not set the password to the password in the Lab because it did not pass the password requirements. I think the account got disabled by not complying to the policy?

Repro steps:
Just follow the lab up to this step.

I reset the password to something stronger and enabled the account again. Ran the sync and the I could login with the account.

**Comment by polichtm** [comment] 2021-03-06 01:38
Hi Ralf,
are you referring to the aduser1 account? 
Where where you trying to set the password for this account and to what value?
rgds
Marcin

**Comment by ervee** [comment] 2021-03-06 19:37
Hi Marcin, yes.
This account is created at Ex. 2, Task 2, step 12.  That did work, but only at Ex. 3, task 3, step 2 I could not use the account because it was disabled or otherwise not usable because the password requirements were not met.
My lab account on azure is closed so I can't redo it all to see if I made an error somewhere though.

**Comment by polichtm** [comment] 2021-03-06 23:51
Hi Ralf,
unfortunately I cannot reproduce this behavior. The account in question is a user object replicated from Active Directory, so it's a subject to AD password policy (more at https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-password-hash-synchronization ). 
In any case, we'll watch for anyone else reporting similar issues - but, for the time being (unless there is a way to reliably reproduce this behavior), we'll close this issue
rgds
Marcin

**Closed by polichtm** 2021-03-06 23:51 UTC
